version: "3.8"

services:
  app:
    image: digital-healthcare:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:6789"
    environment:
      - PORT=${PORT}
      - DBCONNECTION_STRING=${DBCONNECTION_STRING}
      - MONGO_URI=${MONGO_URI}
      - URL=${URL}
      - BCRYPT_SALT_ROUNDS=${BCRYPT_SALT_ROUNDS}
      - JWT_SECRET=${JWT_SECRET}
      - EXPIRESIN=${EXPIRESIN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - .:/app
    command: ["yarn", "start"]
    depends_on:
      - postgres
      - mongo
    restart: "no"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digital-healthcare
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: "no"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: "no"

volumes:
  postgres_data:
  mongo_data:
