# version: '3.8'
# services:
#   app:
#     build: .
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#       - mongo
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: digital_healthcare
#     ports:
#       - '5432:5432'
#   mongo:
#     image: mongo:5
#     ports:
#       - '27017:27017'
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET_KEY=your-secret-key
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=health
    depends_on:
      - postgres
      - mongodb
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=health
  mongodb:
    image: mongo:latest
